### ISSUE TITLE
Suggestion for CI: Only run on push to master OR pull request

### ISSUE THREAD

**Issue by junderw** [rust-bitcoin/rust-bitcoin#1726]
I was noticing that a lot of internal PRs (made by team members) were firing multiple CIs for push and pull_request.

In BitcoinJS we use the following.

```yaml
on:
  push:
    branches:
      - master
  pull_request:
```

I have also considered adding a pattern matching for branches with the prefix `with-ci/**` (edit: looked up the actual syntax) in case we want to test the CI internally before making a PR... but in general we've just tested things out on PRs anyways so never needed it.

Any thoughts?

**Comment by Kixunil** [comment]
Yeah, I'd prefer for pull request since we want to see test status in them but could get annoying if people want to test something on their own branch without bothering us.

**Comment by apoelstra** [comment]
Would this mean that we don't re-run CI when PRs get updated?

**Comment by junderw** [comment]
> Yeah, I'd prefer for pull request since we want to see test status in them but could get annoying if people want to test something on their own branch without bothering us.

@Kixunil This can be done by having some sort of branch prefix or special branch. The above syntax is basically an array in yaml, so you could do multiple filters for deciding which branches will run a CI: See [here](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#using-filters)

```yaml
on:
  push:
    branches:
      - master
      - special-branch # this will also run CI on the special-branch branch
      - 'use-ci/**' # this will run CI on any branch that starts with use-ci/
  pull_request:
```

> Would this mean that we don't re-run CI when PRs get updated?

@apoelstra CI will be re-run with every push to an open PR branch regardless of whether the branch is internal or external.

You can verify this behavior in a recent PR on our repo: https://github.com/bitcoinjs/bitcoinjs-lib/pull/1879

Scrolling down the comments, the 3 commits all ran CI with the above (in OP) configuration.
