### ISSUE TITLE
error: the trait bound `bitcoin::secp256k1::PublicKey: Serialize` is not satisfied

### ISSUE THREAD

**Issue by ssantos21** [rust-bitcoin/rust-bitcoin#1899]
Why is it not possible to serialize `bitcoin::secp256k1::PublicKey` ?
Is there a workaround ?
The code below throws the error:

```
the trait bound `bitcoin::secp256k1::PublicKey: Serialize` is not satisfied
the following other types implement trait `Serialize`:
  &'a T
  &'a mut T
  ()
  (T0, T1)
  (T0, T1, T2)
  (T0, T1, T2, T3)
  (T0, T1, T2, T3, T4)
  (T0, T1, T2, T3, T4, T5)
and 125 others
required for `Vec<bitcoin::secp256k1::PublicKey>` to implement `Serialize`
```

The code:

```rust
use bitcoin::secp256k1::PublicKey;
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize)]
pub struct PrepareSignTxMsg {
    pub input_addrs: Vec<PublicKey>
}
```

```toml
[dependencies]
bitcoin = "0.30.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
```
