### ISSUE TITLE
Use linter to prevent calls to `println`

### ISSUE THREAD

**Issue by tcharding** [rust-bitcoin/rust-bitcoin#4260]
We could use this

```toml
[workspace.lints.clippy]
print_stdout = "deny"
print_stderr = "deny"
```
