### ISSUE TITLE
Can't use latest git version of rust-bitcoin

### ISSUE THREAD

**Issue by eval-exec** [rust-bitcoin/rust-bitcoin#4283]
Hello,

This crate can't be used as `git` dependency as: 
```toml
bitcoin = { package = "bitcoin", git = 'https://github.com/rust-bitcoin/rust-bitcoin', branch = "master" }
```

That will got:

```
❯ cargo check
    Updating git repository `https://github.com/rust-bitcoin/rust-bitcoin`
    Updating crates.io index
error: failed to select a version for `bitcoin-internals`.
    ... required by package `bitcoin v0.33.0-alpha.0 (https://github.com/rust-bitcoin/rust-bitcoin?branch=master#87889955)`
    ... which satisfies git dependency `bitcoin` of package `bitcoin_test v0.1.0 (/tmp/a/bitcoin_test)`
versions that meet the requirements `^0.4.0` are: 0.4.0

the package `bitcoin` depends on `bitcoin-internals`, with features: `hex` but `bitcoin-internals` does not have these features.


failed to select a version for `bitcoin-internals` which could resolve this conflict
```

You can reproduce it by:
```bash
1. cargo new bitcoin-test
2. cd bitcoin-test
```
3. add
```toml
[dependencies]
bitcoin = { package = "bitcoin", git = 'https://github.com/rust-bitcoin/rust-bitcoin', branch = "master" }
```
to `Cargo.toml`
4. cargo check
